# Step 1: Build stage
FROM node:20.11.0-alpine3.19 AS build-stage
WORKDIR /app
COPY package* .
RUN npm install
COPY . .
ENV REACT_APP_DB_URL=http://10.100.102.5:3033/posts
RUN npm run build

# Step 2: Production stage
FROM nginx:1.25.3-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]